import { Metadata } from "next";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Next Js Tutorial - Codeevolution",
    template: "%s | Generated by Vishal Mahale",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue", padding: "2rem" }}>
          <p>Header</p>
        </header>
        {children}
        <footer style={{ backgroundColor: "lightgray", padding: "2rem" }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
